version: "3.7"

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

services:
  #######################################
  # Nginx: web server
  #######################################
  nginx:
    image: nginx:latest
    container_name: lemp_nginx
    restart: always
    volumes:
      - ./www:/var/www/html
      # - ./nginx:/etc/nginx
      - ./nginx/conf/nginx.conf:/etc/nginx/conf/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./logs/nginx:/var/log/nginx
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      - backend
      - frontend

  #######################################
  # Redia: cache && session
  #######################################
  redis:
    image: redis
    container_name: lemp_redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
      - ./redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - /etc/localtime:/etc/localtime:ro
    restart: always
    networks:
      - backend

  #######################################
  # Mariadb: queue database
  #######################################
  db:
    image: mariadb:latest
    container_name: lemp_mariadb
    restart: always
    volumes:
      - ./mysql/initdb:/docker-entrypoint-initdb.d
      - ./mysql/data:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_ROOT_PASSWORD=root_db
      - MYSQL_DATABASE=queue
      - MYSQL_USER=andaman
      - MYSQL_PASSWORD=b8888888
    ports:
      - "3306:3306"
    networks:
      - backend

  #######################################
  # PHP: php v7.3
  #######################################
  php73:
    build: ./php73
    container_name: lemp_php73-fpm
    restart: always
    volumes:
      - ./www:/var/www/html
      - ./php73/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./php73/php.ini:/usr/local/etc/php/php.ini
      - ./logs/php73-fpm:/var/log/php-fpm
    expose:
      - "9000"
      - "22"
    networks:
      - backend

  #######################################
  # Nodejs: queue api
  #######################################
  api:
    build: ./www/kubota/docker/node
    container_name: lemp_api
    restart: always
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./logs/api:/usr/src/app/logs
    links:
      - db
      - redis
    networks:
      - frontend
      - backend

  #######################################
  # PHP Myadmin:
  #######################################
  pma:
    image: phpmyadmin/phpmyadmin
    container_name: lemp_phpmyadmin
    restart: always
    ports:
      - "8000:80"
    environment:
      PMA_HOST: db
    depends_on:
      - db
    links:
      - db
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      - backend
